"""
Datos oficiales de referencia para el módulo Control Sanitario.

Fuentes (Ministerio de Salud de Costa Rica, en uploads/documentation/):
  - DAC anexo 9, Decreto 37308-S — Guía de Inspección para Servicios de
    Alimentación al Público (checklist puntuado del inspector).
  - LS-PG-008 — Lineamientos generales de limpieza y desinfección.

El checklist se extrajo del documento oficial; los puntos críticos exactos
(resaltados en la guía impresa) deben confirmarse contra la versión oficial.
"""

INSPECTION_RANGES = [
    {"min": 81, "max": 100, "label": "Buenas condiciones", "color": "green",
     "detail": "Se notifica por orden sanitaria cualquier incumplimiento para aplicar medidas correctivas."},
    {"min": 70, "max": 80, "label": "Condiciones deficientes", "color": "yellow",
     "detail": "Se giran medidas y orden sanitaria."},
    {"min": 0, "max": 69, "label": "Condiciones inaceptables", "color": "red",
     "detail": "Por riesgo a la salud se puede notificar la suspensión de la actividad hasta corregir."},
]

# Checklist oficial (DAC anexo 9). points=valor del ítem; critical según el
# propio documento (p. ej. agua potable, Art. 10).
INSPECTION_SECTIONS = [{'letter': 'A',
  'title': 'Condiciones físicas y sanitarias generales de las instalaciones',
  'items': [{'article': 'Art. 5',
             'text': 'Distancia mayor o igual a 3m de expendios de agroquímicos que no realicen mezclas y mayor a '
                     '10m de aquellas que realizan mezclas',
             'points': 1,
             'critical': False},
            {'article': 'Art. 6', 'text': 'Libres de residuos y aguas estancadas', 'points': 1, 'critical': False},
            {'article': 'Art. 6',
             'text': 'Zonas verdes y ornamentales recortadas y libres de maleza',
             'points': 1,
             'critical': False},
            {'article': 'Art. 6',
             'text': 'Libres de equipos o materiales en desuso que pueden constituirse en atracción y refugio para '
                     'insectos y roedores',
             'points': 1,
             'critical': False},
            {'article': 'Art. 6',
             'text': 'Mantenimiento adecuado de los conductos o canales exteriores que drenan las aguas, para evitar '
                     'su estancamiento',
             'points': 1,
             'critical': False},
            {'article': 'Art. 7',
             'text': 'El establecimiento se encuentra independiente de viviendas u otras actividades de naturaleza '
                     'distinta',
             'points': 1,
             'critical': False},
            {'article': 'Art. 8',
             'text': 'Cuenta con las áreas claramente definidas de: almacenamiento y conservación, preparación, '
                     'consumo, servicios sanitarios',
             'points': 1,
             'critical': False},
            {'article': 'Art. 8',
             'text': 'Las dimensiones permiten el desarrollo de cada actividad',
             'points': 1,
             'critical': False},
            {'article': 'Art. 10', 'text': 'Disposición de agua potable siempre', 'points': 3, 'critical': True},
            {'article': 'Art. 10',
             'text': 'Agua suficiente para ejecutar todas las operaciones en el establecimiento',
             'points': 3,
             'critical': True},
            {'article': 'Art. 10',
             'text': 'Existe un procedimiento escrito para la higienización de tanques de almacenamiento cuando '
                     'cuenten con estos',
             'points': 2,
             'critical': True},
            {'article': 'Art. 12',
             'text': 'El cableado eléctrico, tomacorrientes, interruptores y enchufes se mantienen en buenas '
                     'condiciones de funcionamiento',
             'points': 2,
             'critical': False},
            {'article': 'Art. 12',
             'text': 'Cuenta con cajas de breaker en buen estado de funcionamiento',
             'points': 1,
             'critical': False},
            {'article': 'Art. 12',
             'text': 'El cableado eléctrico se encuentra entubado',
             'points': 1,
             'critical': False},
            {'article': 'Art. 12',
             'text': 'Tomacorrientes e interruptores se encuentran anclados',
             'points': 1,
             'critical': False}]},
 {'letter': 'B',
  'title': 'Área de preparación de alimentos (Cocina)',
  'items': [{'article': 'Art. 18',
             'text': 'El área de cocina cuenta con zona de preparación previa, zona de preparación intermedia y zona '
                     'de preparación final o se divide el trabajo en etapas (si eventualmente el espacio físico no '
                     'fuera suficiente para hacer la división mencionada), para evitar la contaminación cruzada.',
             'points': 1,
             'critical': False},
            {'article': 'Art. 16',
             'text': 'Deben mantenerse limpios y desinfectados, libres de grasa y sin acumulación de agua',
             'points': 1,
             'critical': False},
            {'article': 'Art. 13',
             'text': 'Deben ser de material impermeable, lisas, fáciles de lavar y desinfectar, de color claro y sin '
                     'grietas',
             'points': 1,
             'critical': False},
            {'article': 'Art. 13',
             'text': 'Los ángulos entre las paredes y pisos permiten la fácil limpieza y desinfección',
             'points': 1,
             'critical': False},
            {'article': 'Art. 14',
             'text': 'Debe tener un diseño que impida la acumulación de suciedad y de materiales lisos',
             'points': 2,
             'critical': False},
            {'article': 'Art. 19',
             'text': 'Están provistas de protección contra insectos y roedores',
             'points': 1,
             'critical': False},
            {'article': 'Art. 19',
             'text': 'El sistema de protección se desmonta con facilidad para su limpieza y mantenimiento',
             'points': 1,
             'critical': False},
            {'article': 'Art. 20',
             'text': 'Son de material liso e impermeable y ajustadas a sus marcos',
             'points': 1,
             'critical': False},
            {'article': 'Art. 20',
             'text': 'Cuentan con cierre automático o el sistema vaivén (cuando aplique)',
             'points': 1,
             'critical': False},
            {'article': 'Art. 21',
             'text': 'Las fuentes lumínicas se encuentran con protectores',
             'points': 1,
             'critical': False},
            {'article': 'Art. 22',
             'text': 'Cuenta con sistema de ventilación natural o artificial, para evitar el calor excesivo y '
                     'condensación de vapores en la cocina',
             'points': 1,
             'critical': False},
            {'article': 'Art. 23',
             'text': 'Los equipos y utensilios que están en contacto directo con los alimentos son de fácil limpieza '
                     'y desinfección',
             'points': 1,
             'critical': False},
            {'article': 'Art. 23',
             'text': 'Son resistentes a la corrosión y no transmiten sustancias toxicas, olores ni sabores a los '
                     'alimentos y no son de madera',
             'points': 1,
             'critical': False},
            {'article': 'Art. 24',
             'text': 'Son de material impermeable, superficie lisa y se mantienen en buen estado de conservación e '
                     'higiene',
             'points': 1,
             'critical': False},
            {'article': 'Art. 24',
             'text': 'Deben estar identificadas según su uso, considerando la naturaleza del producto: para carnes '
                     'crudas, (pollo, bovino y pescado), vegetales y frutas crudas y para alimentos cocidos',
             'points': 2,
             'critical': False},
            {'article': 'Art. 17',
             'text': 'Cuenta con campana de extracción y ductos de extracción ubicados de manera que permitan '
                     'eliminar eficazmente vapores generados por la cocción de los alimentos',
             'points': 2,
             'critical': False},
            {'article': 'Art. 17',
             'text': 'El sistema de extracción cubre la zona destinada a la cocción o fritura',
             'points': 2,
             'critical': False},
            {'article': 'Art. 17',
             'text': 'Se mantienen las campanas y filtros limpios y en buen estado de funcionamiento',
             'points': 1,
             'critical': False},
            {'article': 'Art. 26',
             'text': 'El fregadero se encuentra en buen estado de conservación, limpieza e higiene',
             'points': 1,
             'critical': False},
            {'article': 'Art. 26',
             'text': 'Son de acero inoxidable u otro material resistente y liso',
             'points': 1,
             'critical': False},
            {'article': 'Art. 26',
             'text': 'Su capacidad es acorde con el volumen del servicio',
             'points': 1,
             'critical': False},
            {'article': 'Art. 27',
             'text': 'La vajilla, copas y vasos se guardan boca abajo sobre una superficie limpia, seca y protegida '
                     'de contaminantes y a más de 30 cm sobre el piso',
             'points': 1,
             'critical': False},
            {'article': 'Art. 27',
             'text': 'Los equipos que no se están siendo usados se mantienen cubiertos',
             'points': 1,
             'critical': False},
            {'article': 'Art. 27',
             'text': 'Los equipos y utensilios se encuentran alejados de desagües y de recipientes de residuos',
             'points': 1,
             'critical': False},
            {'article': 'Art. 28', 'text': 'Se mantiene en buen estado y limpia', 'points': 1, 'critical': False},
            {'article': 'Art. 28',
             'text': 'Se conserva en un lugar exclusivo para este uso, libre de polvo y humedad',
             'points': 1,
             'critical': False},
            {'article': 'Art. 28',
             'text': 'Las servilletas de tela se reemplazan para cada cliente',
             'points': 1,
             'critical': False},
            {'article': 'Art. 28',
             'text': 'Los individuales de plástico u otro material se limpian y desinfectan después de cada uso',
             'points': 1,
             'critical': False},
            {'article': 'Art. 29',
             'text': 'A las hortalizas, verduras, y frutas sin procesar, antes de utilizarlas se lavan utilizando '
                     'agentes microbianos de uso en alimentos y debidamente registrados',
             'points': 3,
             'critical': False},
            {'article': 'Art. 29',
             'text': 'Su disposición final está incluido dentro del programa de manejo integral de residuos.',
             'points': 1,
             'critical': False},
            {'article': 'Art. 33',
             'text': 'Los alimentos pre-elaborados y cocinados se conservan tapados, rotulados y en refrigeración',
             'points': 2,
             'critical': False},
            {'article': 'Art. 33',
             'text': 'Los ingredientes crudos o cocidos y embutidos deben mantenerse rotulados y en refrigeración.',
             'points': 2,
             'critical': False},
            {'article': 'Art. 33',
             'text': 'Los productos como cremas a base de leche y huevos, se mantienen en refrigeración',
             'points': 1,
             'critical': False},
            {'article': 'Art. 35',
             'text': 'Los alimentos crudos se almacenan en los equipos de refrigeración en recipientes de material '
                     'resistente y tapados o bolsas plásticas y se colocan separados de los cocidos',
             'points': 2,
             'critical': False},
            {'article': 'Art. 35',
             'text': 'Los utensilios como cuchillos y cucharones se encuentran identificados según su uso en '
                     'productos crudos y cocidos',
             'points': 2,
             'critical': False}]},
 {'letter': 'C',
  'title': 'Del almacenamiento de alimentos',
  'items': [{'article': 'Art. 36',
             'text': 'Se cuenta con un lugar o espacio exclusivo para almacenar productos no perecederos',
             'points': 1,
             'critical': False},
            {'article': 'Art. 36',
             'text': 'Se cuenta con cámara de refrigeración o congelación para almacenar productos perecederos según '
                     'corresponda a la naturaleza del producto',
             'points': 1,
             'critical': False},
            {'article': 'Art. 39',
             'text': 'Construidos de materiales impermeables, antideslizantes, resistentes, fáciles de limpiar y '
                     'desinfectar y se mantienen en buen estado de conservación e higiene',
             'points': 1,
             'critical': False},
            {'article': 'Art. 39',
             'text': 'Sin fracturas, grietas ni irregularidades en su superficie o uniones',
             'points': 1,
             'critical': False},
            {'article': 'Art. 39',
             'text': 'Deben mantenerse limpios y desinfectados',
             'points': 1,
             'critical': False},
            {'article': 'Art. 37',
             'text': 'Deben ser de material impermeable, lisas, fáciles de lavar y desinfectar, de color claro',
             'points': 1,
             'critical': False},
            {'article': 'Art. 37',
             'text': 'Deben estar en buen estado de mantenimiento e higiene',
             'points': 1,
             'critical': False},
            {'article': 'Art. 37',
             'text': 'Los ángulos entre las paredes y pisos permiten la fácil limpieza y desinfección',
             'points': 1,
             'critical': False},
            {'article': 'Art. 38',
             'text': 'Debe tener un diseño que impida la acumulación de suciedad y de materiales lisos',
             'points': 1,
             'critical': False},
            {'article': 'Art. 40',
             'text': 'Es de superficie lisa e impermeable y está ajustada completamente a sus marcos',
             'points': 1,
             'critical': False},
            {'article': 'Art. 41',
             'text': 'Las fuentes lumínicas se encuentran con protectores',
             'points': 1,
             'critical': False},
            {'article': 'Art. 42',
             'text': 'El lugar se encuentra limpio, seco y ventilado',
             'points': 1,
             'critical': False},
            {'article': 'Art. 42', 'text': 'Protegido de posibles plagas', 'points': 2, 'critical': False},
            {'article': 'Art. 42',
             'text': 'Envases tapados e identificados y no estar en contacto con el piso',
             'points': 1,
             'critical': False},
            {'article': 'Art. 42',
             'text': 'Existe control documental en la rotación de los productos',
             'points': 1,
             'critical': False},
            {'article': 'Art. 42',
             'text': 'El producto debe estar sobre estantes o tarimas, separados del piso 0,15 m',
             'points': 1,
             'critical': False},
            {'article': 'Art. 43',
             'text': 'Almacenamiento de alimentos separados de acuerdo a su naturaleza y debidamente identificados',
             'points': 2,
             'critical': False},
            {'article': 'Art. 43',
             'text': 'Alimentos refrigerados a una temperatura igual o menor a 5*C',
             'points': 3,
             'critical': False},
            {'article': 'Art. 43', 'text': 'Alimentos congelados de -12*C a -18*C', 'points': 2, 'critical': False},
            {'article': 'Art. 43',
             'text': 'El equipo de refrigeración no sobrepasa su capacidad',
             'points': 2,
             'critical': False},
            {'article': 'Art. 43',
             'text': 'Carnes colocadas en recipientes o bolsas plásticas',
             'points': 2,
             'critical': False},
            {'article': 'Art. 43',
             'text': 'Los alimentos están colocados separados de manera que permita la circulación de aire frio',
             'points': 1,
             'critical': False}]},
 {'letter': 'D',
  'title': 'Higiene y desinfección, control de plagas y residuos',
  'items': [{'article': 'Art. 60',
             'text': 'El establecimiento cuenta con un programa documentado de higiene y desinfección que incluye '
                     'los procedimientos de limpieza y desinfección',
             'points': 2,
             'critical': False},
            {'article': 'Art. 60',
             'text': 'Se tiene evidencia de la implementación del programa de limpieza y desinfección',
             'points': 2,
             'critical': False},
            {'article': 'Art. 60',
             'text': 'Los productos de limpieza están registrados ante el Ministerio de Salud, identificados y '
                     'correctamente almacenados',
             'points': 1,
             'critical': False},
            {'article': 'Art. 61',
             'text': 'Cuenta con un plan de control de plagas implementado y se lleva un registro de las actividades '
                     'y aplicaciones.',
             'points': 1,
             'critical': False},
            {'article': 'Art. 61',
             'text': 'En caso de la aplicación de plaguicidas, se debe realizar por personal capacitado o por una '
                     'empresa autorizada por el Ministerio de Salud',
             'points': 1,
             'critical': False},
            {'article': 'Art. 61',
             'text': 'Los plaguicidas utilizados están registrados por el Ministerio de Salud',
             'points': 1,
             'critical': False},
            {'article': 'Art. 61',
             'text': 'Los productos químicos se mantienen cerrados, identificados y fuera del área de preparación de '
                     'alimentos',
             'points': 1,
             'critical': False},
            {'article': 'Art. 61',
             'text': 'Se toman las debidas previsiones para evitar el ingreso de animales domésticos, a excepción de '
                     'los perros guías utilizados por las personas no videntes',
             'points': 1,
             'critical': False},
            {'article': 'Art. 62',
             'text': 'Su ubicación no comunica directamente con el área de preparación de alimentos y cuenta con '
                     'ventilación al exterior',
             'points': 2,
             'critical': False},
            {'article': 'Art. 62',
             'text': 'Operan correctamente, se mantienen en buen estado de conservación e higiene',
             'points': 2,
             'critical': False},
            {'article': 'Art. 63',
             'text': 'Los recipientes destinados para los residuos sólidos cuentan con tapa oscilante o similar que '
                     'evite el contacto con las manos y con bolsa plástica',
             'points': 2,
             'critical': False},
            {'article': 'Art. 63',
             'text': 'Los recipientes se encuentran ubicados en un lugar donde no sean fuente de contaminación',
             'points': 2,
             'critical': False},
            {'article': 'Art. 63',
             'text': 'Los residuos líquidos se conducen correctamente hacia el sistema de tratamiento o al '
                     'alcantarillado sanitario, los conductos están protegidos por rejillas para impedir el ingreso '
                     'de roedores',
             'points': 2,
             'critical': False},
            {'article': 'Art. 63',
             'text': 'Se cuenta con trampas de grasas y aceites, y se mantienen en buen estado de funcionamiento e '
                     'higiene',
             'points': 2,
             'critical': False},
            {'article': 'Art. 63',
             'text': 'Se destina un área aislada, limpia y protegida contra plagas para el almacenamiento temporal '
                     'de residuos sólidos',
             'points': 1,
             'critical': False}]},
 {'letter': 'E',
  'title': 'Personal y manipulación de alimentos',
  'items': [{'article': 'Art. 4',
             'text': 'El personal cuenta con el carné de manipulador de alimentos vigente',
             'points': 3,
             'critical': False},
            {'article': 'Art. 57',
             'text': 'El propietario o administrador toma medidas para evitar que el personal que muestre signos de '
                     'enfermedad o tenga heridas, infecciones cutáneas, llagas o diarrea, trabaje en zonas de '
                     'manipulación de alimentos',
             'points': 2,
             'critical': False},
            {'article': 'Art. 58',
             'text': 'El personal mantiene las uñas limpias, recortadas, sin esmalte, no utilizan maquillaje y no '
                     'portan joyas y se observan buenos hábitos de higiene. Esto aplica para el área de preparación '
                     'de alimentos.',
             'points': 2,
             'critical': False},
            {'article': 'Art. 58',
             'text': 'El personal encargado de caja que manipula dinero, no debe participar en actividades '
                     'relacionadas con la manipulación de alimentos durante el tiempo que realiza esta función',
             'points': 1,
             'critical': False},
            {'article': 'Art. 59',
             'text': 'El personal del área de preparación de alimentos lleva ropa de trabajo limpia y en buen estado '
                     'de conservación, cobertor de cabello, calzado cerrado de material no absorbente',
             'points': 2,
             'critical': False}]},
 {'letter': 'F',
  'title': 'Área de consumo y servicio',
  'items': [{'article': 'Art. 45',
             'text': 'El espacio permite la circulación de los usuarios y se mantiene en buenas condiciones de '
                     'limpieza',
             'points': 1,
             'critical': False},
            {'article': 'Art. 45',
             'text': 'Mobiliario de material resistente, de fácil limpieza',
             'points': 1,
             'critical': False},
            {'article': 'Art. 45',
             'text': 'Los pisos, paredes y cielo raso se mantienen en buen estado de conservación e higiene',
             'points': 1,
             'critical': False},
            {'article': 'Art. 47',
             'text': 'Los equipos utilizados para mantener alimentos calientes alcanzan una temperatura mayor o '
                     'igual a 60*C',
             'points': 2,
             'critical': False},
            {'article': 'Art. 47',
             'text': 'Si cuenta con servicio tipo buffet cada recipiente con comida cuenta con su propio utensilio '
                     'para servir',
             'points': 2,
             'critical': False},
            {'article': 'Art. 47',
             'text': 'Las urnas o exhibidores de alimentos como pollo frito, rostizado o carnes preparadas cuentan '
                     'con bombillos o reflectores protegidos y alcanzan la temperatura de 60*C',
             'points': 2,
             'critical': False},
            {'article': 'Art. 48',
             'text': 'Las vitrinas refrigeradas para exhibición de alimentos preparados se mantienen en buen estado '
                     'de funcionamiento e higiene',
             'points': 2,
             'critical': False},
            {'article': 'Art. 49',
             'text': 'Las vitrinas no refrigeradas para exhibición de alimentos se mantienen en buen estado de '
                     'funcionamiento e higiene',
             'points': 1,
             'critical': False},
            {'article': 'Art. 50',
             'text': 'Cuando se utilicen utensilios de material desechable se descartan inmediatamente',
             'points': 1,
             'critical': False},
            {'article': 'Art. 50',
             'text': 'Los recipientes dispensadores de salsas, aderezos, mayonesa, azúcar u otros se mantienen '
                     'rotulados y en buen estado de conservación e higiene y cerrados',
             'points': 1,
             'critical': False},
            {'article': 'Art. 50',
             'text': 'Se mantienen en refrigeración según la naturaleza de su contenido',
             'points': 2,
             'critical': False},
            {'article': 'Art. 52',
             'text': 'La vajilla, cubiertos y vasos se encuentran limpios, secos y en buen estado de conservación e '
                     'higiene',
             'points': 1,
             'critical': False},
            {'article': 'Art. 53',
             'text': 'Se elabora a partir de agua potable o proviene de una fábrica autorizada por el Ministerio de '
                     'Salud',
             'points': 2,
             'critical': True},
            {'article': 'Art. 53',
             'text': 'Se manipula con pinzas y los recipientes se mantienen en buen estado e higiene',
             'points': 1,
             'critical': False},
            {'article': 'Art. 53',
             'text': 'El hielo utilizado para enfriamiento de bebidas o copas no se usa para consumo humano',
             'points': 1,
             'critical': False}]},
 {'letter': 'G',
  'title': 'Servicio express',
  'items': [{'article': 'Art. 56',
             'text': 'Se utilizan envases desechables de primer uso para entregar los alimentos al cliente',
             'points': 1,
             'critical': False},
            {'article': 'Art. 56', 'text': 'Salsas y aderezos debidamente empacados', 'points': 1, 'critical': False},
            {'article': 'Art. 56',
             'text': 'Los contenedores térmicos del vehículo cuentan con cierre hermético y seguro',
             'points': 1,
             'critical': False}]},
 {'letter': 'H',
  'title': 'Servicios de catering',
  'items': [{'article': 'Art. 55',
             'text': 'Los vehículos que transporten alimentos se mantienen en buenas condiciones de higiene',
             'points': 2,
             'critical': False},
            {'article': 'Art. 55',
             'text': 'Cuentan con carrocería cerrada de forma que impidan el ingreso de contaminantes externos',
             'points': 1,
             'critical': False},
            {'article': 'Art. 55',
             'text': 'Los recipientes utilizados que tengan contacto directo con los alimentos deben ser de '
                     'materiales resistentes, de fácil limpieza y desinfección y no transmitir sustancias toxicas, '
                     'olores o sabores a los mismos',
             'points': 1,
             'critical': False},
            {'article': 'Art. 55',
             'text': 'Los utensilios y mantelería se transportan debidamente protegidos de posibles contaminantes',
             'points': 1,
             'critical': False}]}]

CHLORINE_REFERENCE = {
    "commercial_range": "En Costa Rica el cloro comercial suele tener 3.5% a 5%.",
    "note": "Preparar la solución el mismo día. Para superficies en contacto con alimentos, seguir la ficha técnica del producto REGISTRADO ante el Ministerio de Salud.",
    "examples": [
        {"use": "Superficies generales (0.1%)", "target": 0.1, "ml_per_litre_at_5pct": 20, "hint": "≈ 4 cucharaditas por litro (cloro al 5%)"},
        {"use": "Desinfección (0.5%)", "target": 0.5, "ml_per_litre_at_5pct": 100, "hint": "≈ 6 cucharadas por litro (cloro 5%); 143 ml/L si el cloro es 3.5%"},
        {"use": "Fluidos biológicos (2%)", "target": 2.0, "ml_per_litre_at_5pct": 400, "hint": "400 ml/L (cloro 5%); 570 ml/L si el cloro es 3.5%"},
    ],
}

PROCEDURE_TIPS = [
    "Primero LIMPIAR (remover materia orgánica) y luego DESINFECTAR.",
    "Seguir siempre las instrucciones del fabricante del desinfectante.",
    "Preparar la solución de cloro el mismo día que se usa.",
    "Usar equipo de protección personal (EPP) según el tipo de limpieza.",
    "Nunca sacudir los paños o toallas usados para limpiar y desinfectar.",
    "Al terminar, verificar que los desagües queden despejados.",
    "Usar productos de limpieza REGISTRADOS ante el Ministerio de Salud, identificados y bien almacenados.",
]

GUIDE_DOCS = [
    {"file": "DAC_anexo_9_decreto_37308_s_servicios_alimentacion_publico.docx",
     "title": "Guía de Inspección — Servicios de Alimentación (Decreto 37308-S, anexo 9)",
     "kind": "Guía de inspección oficial",
     "summary": "Es el checklist puntuado que usa el inspector del Ministerio de Salud. Evalúa instalaciones, cocina, almacenamiento, higiene/desinfección, personal y servicio. La nota final define si el establecimiento está en buenas condiciones, deficientes o inaceptables.",
     "maps": ["Úsalo en Autoinspección para pre-evaluarte", "Protocolo cubre el programa de higiene", "Temperaturas cubre cadena de frío/calor", "Plagas cubre el control de plagas"]},
    {"file": "ls_pg_008_lineamientos_generales_limpieza_desinfeccion_espacios_fisicos.pdf",
     "title": "LS-PG-008 — Limpieza y desinfección de espacios físicos",
     "kind": "Lineamiento del Ministerio de Salud",
     "summary": "Indica el procedimiento correcto de limpieza y desinfección: primero limpiar y luego desinfectar, uso de EPP, y las diluciones de cloro (hipoclorito de sodio) para distintos usos.",
     "maps": ["Diluciones de cloro en la Calculadora", "Recordatorios de procedimiento", "Concentración/tiempo de contacto en cada tarea del Protocolo"]},
]
